import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import Database from 'better-sqlite3'
import { applyMigrations, migrations } from '../lib/migrations.mjs'

test('migra o schema legado uma única vez e preserva os dados', () => {
  const db = new Database(':memory:')
  try {
    const schema = readFileSync(new URL('../database/schema.sql', import.meta.url), 'utf8')
      .split('\n')
      .filter((line) => !line.trim().toUpperCase().startsWith('PRAGMA'))
      .join('\n')
    db.exec(schema)
    const clienteId = Number(db.prepare(`INSERT INTO clientes (tenant_id, usuario_id, nome) VALUES (1, 1, 'Cliente teste')`).run().lastInsertRowid)
    const filamentoId = Number(db.prepare(`
      INSERT INTO filamentos (
        tenant_id, usuario_id, material, cor, peso_rolo_gramas, preco_rolo, estoque_gramas
      ) VALUES (1, 1, 'PLA', 'Preto', 1000, 90, 750)
    `).run().lastInsertRowid)
    const pedidoId = Number(db.prepare(`INSERT INTO pedidos (
      tenant_id, usuario_id, cliente_id, nome_da_peca, tempo_impressao_horas, valor_total_cobrado
    ) VALUES (1, 1, ?, 'Ímã Bem-Estar', 10, 35)`).run(clienteId).lastInsertRowid)
    db.prepare(`INSERT INTO pedido_filamentos
      (pedido_id, filamento_id, peso_gasto_gramas, custo_calculado) VALUES (?, ?, 100, 9)`)
      .run(pedidoId, filamentoId)

    applyMigrations(db)
    applyMigrations(db)

    const columns = db.prepare(`PRAGMA table_info(pedidos)`).all().map((column) => column.name)
    assert.ok(columns.includes('orcamento_status'))
    assert.ok(columns.includes('tempo_real_horas'))
    assert.equal(db.prepare('SELECT COUNT(*) AS total FROM schema_migrations').get().total, migrations.length)
    assert.equal(db.prepare('SELECT nome FROM clientes WHERE nome = ?').get('Cliente teste').nome, 'Cliente teste')
    assert.equal(db.prepare('SELECT COUNT(*) AS total FROM impressoras').get().total, 2)
    assert.equal(db.prepare('SELECT COUNT(*) AS total FROM lotes_filamento').get().total, 1)
    assert.equal(db.prepare('SELECT saldo_gramas FROM lotes_filamento').get().saldo_gramas, 750)
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'parcelas_receber'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'auditoria'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'importacoes_planilha'`).get())
    assert.ok(columns.includes('codigo_externo'))
    assert.ok(columns.includes('materiais_avulsos_por_unidade'))
    assert.ok(columns.includes('horas_trabalho_ativo'))
    assert.ok(columns.includes('setup_projeto'))
    assert.ok(columns.includes('margem_perdas'))
    const expenseColumns = db.prepare(`PRAGMA table_info(despesas)`).all().map((column) => column.name)
    assert.ok(expenseColumns.includes('grupo_parcelamento'))
    assert.ok(expenseColumns.includes('total_parcelas'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'modelos_orcamento'`).get())
    const printerColumns = db.prepare(`PRAGMA table_info(impressoras)`).all().map((column) => column.name)
    assert.ok(printerColumns.includes('bico_atual'))
    assert.ok(printerColumns.includes('horas_base'))
    assert.ok(printerColumns.includes('intervalo_manutencao_horas'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'manutencoes_impressora'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'despesas_recorrentes'`).get())
    assert.ok(expenseColumns.includes('despesa_recorrente_id'))
    assert.ok(expenseColumns.includes('competencia_chave'))
    const recorrenciaId = Number(db.prepare(`
      INSERT INTO despesas_recorrentes (
        tenant_id, usuario_id, categoria, descricao, valor, dia_vencimento,
        forma_pagamento, inicia_em
      ) VALUES (1, 1, 'Software', 'Sistema mensal', 20, 10, 'Cartão', '2026-09-01')
    `).run().lastInsertRowid)
    const inserirCompetencia = db.prepare(`
      INSERT INTO despesas (
        tenant_id, usuario_id, categoria, descricao, valor, data_despesa,
        despesa_recorrente_id, competencia_chave
      ) VALUES (1, 1, 'Software', 'Sistema mensal', 20, '2026-09-01', ?, '2026-09')
    `)
    inserirCompetencia.run(recorrenciaId)
    assert.throws(() => inserirCompetencia.run(recorrenciaId), /UNIQUE constraint failed/)
    const tenantColumns = db.prepare(`PRAGMA table_info(tenants)`).all().map((column) => column.name)
    assert.ok(tenantColumns.includes('meta_lucro_mensal'))
    assert.ok(tenantColumns.includes('meta_pedidos_mensal'))
    assert.ok(tenantColumns.includes('dias_cliente_inativo'))
    assert.ok(tenantColumns.includes('dias_followup_orcamento'))
    assert.ok(tenantColumns.includes('dias_pos_venda'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'tarefas_agenda'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'avaliacoes_pedido'`).get())
    assert.ok(columns.includes('quantidade_produzida'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'entregas_pedido'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'fornecedores'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'compras'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'compra_itens'`).get())
    assert.ok(expenseColumns.includes('compra_id'))
    const purchaseColumns = db.prepare(`PRAGMA table_info(compras)`).all().map((column) => column.name)
    assert.ok(purchaseColumns.includes('parcelas'))
    assert.ok(columns.includes('produto_id'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'produtos_catalogo'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'produto_versoes'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'produto_versao_itens'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'ocorrencias_qualidade'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'expedicoes'`).get())
    const occurrenceColumns = db.prepare(`PRAGMA table_info(ocorrencias_qualidade)`).all().map((column) => column.name)
    assert.ok(occurrenceColumns.includes('tarefa_id'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'lotes_producao'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'portal_links'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'extrato_importacoes'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'extrato_lancamentos'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'inventarios'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'inventario_itens'`).get())
    const userColumns = db.prepare(`PRAGMA table_info(usuarios)`).all().map((column) => column.name)
    const clientColumns = db.prepare(`PRAGMA table_info(clientes)`).all().map((column) => column.name)
    assert.ok(userColumns.includes('ultimo_acesso_em'))
    assert.ok(userColumns.includes('senha_alterada_em'))
    assert.ok(clientColumns.includes('anonimizado_em'))
    assert.ok(tenantColumns.includes('retencao_backups'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'sessoes'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'tentativas_login'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'backups_registro'`).get())
    assert.ok(tenantColumns.includes('mei_inicio_em'))
    assert.ok(tenantColumns.includes('mei_limite_anual'))
    assert.ok(tenantColumns.includes('mei_natureza_padrao'))
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'receitas_fiscais'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'obrigacoes_fiscais'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'whatsapp_envios'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'arquivos_producao'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'produto_checklist_itens'`).get())
    assert.ok(db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'pedido_checklist_respostas'`).get())
    const productVersionColumns = db.prepare(`PRAGMA table_info(produto_versoes)`).all().map((column) => column.name)
    assert.ok(productVersionColumns.includes('impressora_preferida_id'))
    assert.ok(productVersionColumns.includes('diametro_bico_mm'))
    assert.ok(productVersionColumns.includes('altura_camada_mm'))
    assert.ok(productVersionColumns.includes('unidades_por_placa'))
    assert.ok(productVersionColumns.includes('perfil_fatiamento'))
    assert.ok(productVersionColumns.includes('placa_referencia'))
    const backupColumns = db.prepare(`PRAGMA table_info(backups_registro)`).all().map((column) => column.name)
    assert.ok(backupColumns.includes('externo_status'))
    const produtoMigrado = db.prepare(`SELECT id FROM produtos_catalogo WHERE nome = 'Ímã Bem-Estar'`).get()
    assert.ok(produtoMigrado)
    assert.equal(db.prepare('SELECT produto_id FROM pedidos WHERE id = ?').get(pedidoId).produto_id, produtoMigrado.id)
    assert.equal(db.prepare('SELECT COUNT(*) AS total FROM produto_versoes WHERE produto_id = ?').get(produtoMigrado.id).total, 1)
    assert.equal(db.prepare(`SELECT quantidade_por_unidade FROM produto_versao_itens WHERE tipo_item = 'Filamento'`).get().quantidade_por_unidade, 100)
  } finally {
    db.close()
  }
})
